version: 1.0.{build}
configuration:
  - Release

build:
  verbosity: normal

after_test:
  - md LauncherRelease
  - (robocopy *.exe *.dll "%CD%\Launcher\Launcher\bin\Release" "%CD%\LauncherRelease") ^& exit 0
  
artifacts:
  - path: LauncherRelease
