version: 1.0.{build}
build:
  project: Launcher\Launcher.sln
  
configuration:
  - Release

build:
  verbosity: normal

after_test:
  - md LauncherRelease
  - xcopy "%CD%\Launcher\Launcher\bin\Release\*.exe" "%CD%\LauncherRelease" /y
  - xcopy "%CD%\Launcher\Launcher\bin\Release\*.dll" "%CD%\LauncherRelease" /y
  
artifacts:
  - path: LauncherRelease
